backend:
  name: gitlab
  repo: triaa-studio/triaa-studio
  branch: main
  # when changing this remember to add Oauth credentials on netlify
local_backend:
  url: http://localhost:8081/api/v1

media_folder: 'src/assets/images'
public_folder: '~/assets/images'

collections:
  - name: 'pages'
    label: 'Pages'
    # INFO: Images stored in `/public`, because images stored in /assets isn't being shown after building, (image src from
    # frontmatter only, `assets` works for md body though)
    files:
      - label: 'Homepage'
        name: 'homepage'
        file: 'src/content/decap_statics/homepage.md'
        media_folder: '../../../public/images/'
        public_folder: '/images'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - label: 'Slider Images'
            name: 'slides'
            widget: 'list'
            summary: '{{fields.alt}}'
            fields:
              - label: 'Image'
                name: 'src'
                widget: 'image'
                choose_url: true
              - { label: 'Image short description', name: 'alt', widget: 'string' }
          - name: 'heroSection'
            label: 'Main Entry Section'
            widget: 'object'
            collapsed: true
            fields:
              - name: 'title'
                label: 'title'
                widget: 'string'
              - name: 'description'
                label: 'Description'
                widget: 'text'
          - name: 'cta'
            label: 'Who We are '
            widget: 'object'
            collapsed: true
            fields:
              - name: 'heading'
                label: 'Heading'
                widget: 'string'
              - name: 'description'
                label: 'Description'
                widget: 'text'
              - name: 'button'
                label: 'button'
                widget: 'object'
                fields:
                  - name: 'text'
                    label: 'CTA Text'
                    widget: 'string'
                    required: true
                  - name: 'link'
                    label: 'Link'
                    widget: 'string'
                    required: false
          - label: 'Featured Works'
            name: 'products'
            widget: 'list'
            summary: '{{fields.title}}'
            fields:
              - label: 'Image'
                name: 'image'
                widget: 'image'
                choose_url: true
              - { label: 'Image short description', name: 'altText', widget: 'string' }
              - { label: 'Title Prefix', name: 'preTitle', widget: 'string' }
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Link', name: 'url', widget: 'string' }

          - label: 'Images'
            name: 'images'
            widget: 'list'
            fields:
              - { label: 'Image short description', name: 'alt', widget: 'string' }
              - label: 'Image'
                name: 'src'
                widget: 'image'
                choose_url: true
              - {
                  label: 'Youtube Video Id',
                  name: 'videoId',
                  widget: 'string',
                  hint: ' HELPER: **`dQw4w9WgXcQ`** in https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                }

      - label: 'Technology'
        name: 'technology'
        file: 'src/content/decap_statics/technology.md'
        media_folder: '../../../public/images/technology'
        public_folder: '/images/technology'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Summary', name: 'summary', widget: 'text' }
          - label: 'Slider Contents'
            name: 'content'
            widget: 'list'
            summary: '{{fields.alt}}'
            fields:
              - { label: 'Description', name: 'description', widget: 'string' }
              - { label: 'Image alt', name: 'alt', widget: 'string' }
              - label: 'Image'
                name: 'thumbnailSrc'
                widget: 'image'
                choose_url: true
              - {
                  label: 'Youtube Video Id',
                  name: 'youtubeId',
                  widget: 'string',
                  hint: ' HELPER: **`dQw4w9WgXcQ`** in https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                }

      - label: 'Videos'
        name: 'videos'
        file: 'src/content/decap_statics/videos-page.md'
        media_folder: '../../../public/images/videos'
        public_folder: '/images/videos'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Summary', name: 'summary', widget: 'text' }
          - label: 'Slider Contents'
            name: 'content'
            widget: 'list'
            summary: '{{fields.alt}}'
            fields:
              - { label: 'Description', name: 'description', widget: 'string' }
              - { label: 'Image alt', name: 'alt', widget: 'string' }
              - label: 'Image'
                name: 'thumbnailSrc'
                widget: 'image'
                choose_url: true
              - {
                  label: 'Youtube Video Id',
                  name: 'youtubeId',
                  widget: 'string',
                  hint: ' HELPER: **`dQw4w9WgXcQ`** in https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                }
